'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useStudio } from '../components/StudioProvider';
import { Cover, Header, Icon } from '../components/Design';
import { formats } from '../domain';

export default function BrandPage() {
  const {state,command,pending}=useStudio(); const brand=state.brand;const [voice,setVoice]=useState(brand.voice);const [rule,setRule]=useState('');const [styles,setStyles]=useState<Record<string,string>>({});
  useEffect(()=>{setVoice(brand.voice);setStyles(Object.fromEntries(brand.styles.map(style=>[style.format,style.guidance])))},[brand]);
  const reference=state.posts.find(post=>post.id===brand.reference.postId);
  return <><div className="grid2"><section className="card pad sec"><Header title="Voice"/><textarea disabled={!state.permissions?.['brand.edit']} rows={5} aria-label="Brand voice" value={voice} onChange={event=>setVoice(event.target.value)} onBlur={()=>{if(voice!==brand.voice)void command('brand',{key:'voice',value:voice})}}/><span className="small muted">The AI writes every caption in this voice.</span></section><section className="card pad sec"><Header title="Never say"><span className="chip red r">Phrase checks + review</span></Header>{brand.never.map((text,index)=><div className="never" key={`${text}-${index}`}><Icon name="x"/><span>{text}</span><button aria-label="Remove rule" disabled={pending || !state.permissions?.['brand.edit']} onClick={()=>void command('brand',{action:'remove-rule',id:index})}><Icon name="x"/></button></div>)}<form className="addtopic" style={{maxWidth:'none'}} onSubmit={async event=>{event.preventDefault();if(await command('brand',{action:'add-rule',value:rule}))setRule('')}}><input placeholder="Add a rule" aria-label="Add a never-say rule" value={rule} onChange={event=>setRule(event.target.value)}/><button className="btn ghost" disabled={pending || !state.permissions?.['brand.edit']}><Icon name="plus"/>Add</button></form></section></div><section className="sec"><Header title="Style for each post type"/><div className="grid3">{brand.styles.map(style=><div className="card pad stylec" key={style.format}><div className="sechead"><span className="chip"><Icon name={formats[style.format].icon}/>{formats[style.format].label}</span><b>{style.name}</b></div><textarea disabled={!state.permissions?.['brand.edit']} rows={4} aria-label={`${style.name} style`} value={styles[style.format]||''} onChange={event=>setStyles({...styles,[style.format]:event.target.value})} onBlur={()=>{if(styles[style.format]!==style.guidance)void command('brand',{key:`style:${style.format}`,value:styles[style.format]})}}/></div>)}</div></section><section className="card pad sec"><Header title="Learn from this post"><span className="chip ai r"><Icon name="spark"/>Reference guidance</span></Header>{reference && <div className="rowi" style={{border:0,padding:0}}><Cover bookId={reference.bookId}/><span className="t"><b>{reference.title}</b><small>{reference.platform} · {brand.reference.note}</small></span><Link className="btn sm ghost" href="/results">Change</Link></div>}</section></>;
}
