'use client';
import { useEffect, useState } from 'react';
import { useStudio } from '../components/StudioProvider';
import { Chip, Cover, DueChip, Empty, Icon, Meta, Who } from '../components/Design';
import { getBook, sources } from '../domain';
import type { Post, Source } from '../types';

function IdeaCard({ post }: { post: Post }) {
  const { state, command, pending, openPost } = useStudio();
  const [noteOpen,setNoteOpen]=useState(false); const [note,setNote]=useState(post.note||'');
  useEffect(() => setNote(post.note || ''), [post.note]);
  const selected = post.stage !== 'idea'; const busy = ['generating','revision'].includes(post.stage);
  const book = getBook(state,post.bookId);
  const hasJob = state.activity.some(item => item.postId === post.id && item.status && ['queued','running','waiting','retry_pending'].includes(item.status));
  return <article className={`idea ${post.human?'human':''} ${selected?'selected-idea':''}`}><div className="art" style={{background:book.colors[0]}}><Cover bookId={post.bookId}/><span className="tag">{post.human?<Who kind="team"/>:<span className="who who-ai"><Icon name={sources[post.source].icon}/>{sources[post.source].label}</span>}</span>{selected && <span className="selected-flag"><Icon name="check"/>{busy?'Generating':'Selected'}</span>}</div><div className="bdy"><h3>{post.title}</h3><div className="whyl"><Icon name={post.human?'user':'spark'}/><span>{post.reason}</span></div><Meta post={post}/><div className="tools"><Chip>{post.event}</Chip><DueChip post={post}/></div>{post.note && <div className="notepill"><Icon name="user"/><span>{post.note}</span></div>}
    {!selected && <><div className="refine"><button className="btn ghost sm" disabled={pending || hasJob || !state.permissions?.['ideas.suggest']} onClick={() => void command('posts',{action:'new-angle',id:post.id,version:post.version})}><Icon name="retry"/>New angle</button><button className="btn ghost sm" onClick={() => setNoteOpen(!noteOpen)}><Icon name="edit"/>{post.note?'Edit your input':'Add your input'}</button></div>{noteOpen && <form className="noteform" onSubmit={async event => { event.preventDefault(); if(await command('posts',{action:'note',id:post.id,version:post.version,note}))setNoteOpen(false); }}><input value={note} maxLength={1000} onChange={event => setNote(event.target.value)} placeholder="Audience, angle, or extra context" aria-label="Your input for the AI"/><button className="btn sm" disabled={pending}><Icon name="check"/></button></form>}</>}
    <div className="acts">{selected ? <><button className="btn" onClick={() => openPost(post.id)}>{busy?<><Icon name="spark"/>Generating…</>:<><Icon name="check"/>Selected</>}</button><button className="btn ghost" disabled={pending || busy || !state.permissions?.['ideas.pick']} onClick={() => void command('posts',{action:'unpick',id:post.id,version:post.version})}>Back to Ideas</button></> : <><button className="btn ghost" disabled={pending || !state.permissions?.['content.archive']} onClick={() => void command('posts',{action:'skip',id:post.id,version:post.version})}><Icon name="x"/>Skip</button><button className="btn" disabled={pending || !state.permissions?.['ideas.pick']} onClick={() => void command('posts',{action:'pick',id:post.id,version:post.version})}><Icon name="check"/>Pick</button></>}</div>
  </div></article>;
}

export default function IdeasPage() {
  const { state, command, pending } = useStudio(); const [filter,setFilter]=useState(''); const [topic,setTopic]=useState('');
  const all = state.posts.filter(post => post.stage === 'idea' || post.stage === 'selected' || ['generating','revision'].includes(post.stage) && !post.media?.length);
  const selected = all.filter(post => post.stage !== 'idea');
  const list = all.filter(post => !filter || (filter === 'selected' ? post.stage !== 'idea' : post.source === filter));
  const picked = selected.filter(post => post.stage === 'selected');
  return <><div className="tools">{[['','All'],['calendar','Calendar'],['news','News'],['team','Team'],['selected','Selected']].map(([value,label]) => <button key={label} className={`fchip ${filter===value?'on':''}`} onClick={() => setFilter(value)}>{value && value !== 'selected' && <Icon name={sources[value as Source].icon}/>} {label} <span className="n">{value === 'selected' ? selected.length : value ? all.filter(post => post.source===value).length : all.length}</span></button>)}<form className="addtopic" style={{marginLeft:'auto'}} onSubmit={async event => {event.preventDefault(); if(await command('posts',{action:'create',title:topic}))setTopic('');}}><input placeholder="Add your own topic" aria-label="Add your own topic" value={topic} maxLength={180} onChange={event => setTopic(event.target.value)}/><button className="btn" disabled={pending || !state.permissions?.['ideas.create']}><Icon name="plus"/>Add</button></form></div><div className="legend"><button className="btn ai sm" disabled={pending || !state.permissions?.['ideas.suggest']} onClick={() => void command('posts',{action:'suggest'})}><Icon name="spark"/>Suggest from team topics</button><span><Who kind="ai"/> Suggested by AI</span><span><Who kind="team"/> Added by your team</span></div>{list.length ? <div className="ideas">{list.map(post => <IdeaCard key={post.id} post={post}/>)}</div> : <Empty title={filter==='selected'?'No selected ideas':'No new ideas'} detail="Pick a topic to prepare its caption and media."/>}{picked.length > 0 && <div className="tray"><span className="t"><b>{picked.length} selected</b><small>Prepare captions first, then add media to send posts to Review.</small></span><button className="btn lg" disabled={pending || !state.permissions?.['content.generate']} onClick={() => void command('posts',{action:'generate-all'})}><Icon name="spark"/>Generate captions</button></div>}</>;
}
