'use client';
import { useState } from 'react';
import { useStudio } from '../components/StudioProvider';
import { Chip, Cover, DueChip, Empty, Icon, Meta, Who } from '../components/Design';
import { getBook, sources } from '../domain';
import type { Post, Source } from '../types';

function IdeaCard({ post }: { post: Post }) {
  const { state, command, pending } = useStudio(); const [noteOpen,setNoteOpen]=useState(false); const [note,setNote]=useState(post.note||'');
  const book=getBook(state,post.bookId);
  return <article className={`idea ${post.human?'human':''}`}><div className="art" style={{background:book.colors[0]}}><Cover bookId={post.bookId}/><span className="tag">{post.human?<Who kind="team"/>:<span className="who who-ai" style={{background:'var(--surf)'}}><Icon name={sources[post.source].icon}/>{sources[post.source].label}</span>}</span></div><div className="bdy"><h3>{post.title}</h3><div className="whyl"><Icon name={post.human?'user':'spark'}/><span>{post.reason}</span></div><Meta post={post}/><div style={{display:'flex',gap:5,flexWrap:'wrap'}}><Chip>{post.event}</Chip><DueChip post={post}/></div>{post.note && <div className="notepill"><Icon name="user"/><span>{post.note}</span></div>}{<><div className="refine"><button className="btn ghost sm" disabled={pending || !state.permissions?.['ideas.suggest']} onClick={()=>void command('posts',{action:'new-angle',id:post.id})}><Icon name="retry"/>New angle</button><button className="btn ghost sm" onClick={()=>setNoteOpen(!noteOpen)}><Icon name="edit"/>{post.note?'Edit your input':'Add your input'}</button></div>{noteOpen && <form className="noteform" onSubmit={async event=>{event.preventDefault();if(await command('posts',{action:'note',id:post.id,version:post.version,note}))setNoteOpen(false)}}><input value={note} onChange={event=>setNote(event.target.value)} placeholder="e.g. Mention the new paperback cover" aria-label="Your input for the AI"/><button className="btn sm" disabled={pending}><Icon name="check"/></button></form>}</>}<div className="fit"><span>Team topic · human review required</span></div><div className="acts"><button className="btn ghost" disabled={pending || !state.permissions?.['content.archive']} onClick={()=>void command('posts',{action:'skip',id:post.id})}><Icon name="x"/>Skip</button><button className="btn" disabled={pending || !state.permissions?.['ideas.pick']} onClick={()=>void command('posts',{action:'pick',id:post.id})}><Icon name="check"/>Pick</button></div></div></article>;
}
export default function IdeasPage() {
  const { state, command, pending } = useStudio(); const [source,setSource]=useState(''); const [topic,setTopic]=useState('');
  const all=state.posts.filter(post=>post.stage==='idea'); const list=all.filter(post=>!source||post.source===source); const selected=state.posts.filter(post=>post.stage==='selected');
  return <><div className="tools">{[['','All'],['calendar','Calendar'],['news','News'],['team','Team']].map(([value,label])=><button key={label} className={`fchip ${source===value?'on':''}`} onClick={()=>setSource(value)}>{value && <Icon name={sources[value as Source].icon}/>} {label} <span className="n">{value?all.filter(post=>post.source===value).length:all.length}</span></button>)}<form className="addtopic" style={{marginLeft:'auto'}} onSubmit={async event=>{event.preventDefault();if(await command('posts',{action:'create',title:topic}))setTopic('')}}><input placeholder="Add your own topic" aria-label="Add your own topic" value={topic} onChange={event=>setTopic(event.target.value)}/><button className="btn" disabled={pending || !state.permissions?.['ideas.create']} type="submit"><Icon name="plus"/>Add</button></form></div><div className="legend"><button className="btn ai sm" disabled={pending || !state.permissions?.['ideas.suggest']} onClick={() => void command('posts', { action: 'suggest' })}><Icon name="spark"/>Suggest from team topics</button><span><Who kind="ai"/> Suggested by AI</span><span><Who kind="team"/> Added by your team</span><span className="muted">Every idea shows why it appeared</span></div>{list.length?<div className="ideas">{list.map(post=><IdeaCard post={post} key={post.id}/>)}</div>:<Empty title="No new ideas" detail="Add a team topic, then ask AI for suggestions."/>}{selected.length>0 && <div className="tray"><span className="covs">{selected.map(post=><Cover bookId={post.bookId} key={post.id}/>)}</span><span className="t"><b>{selected.length} picked</b><small>Only picked ideas are made. Cost shows once each is ready.</small></span><button className="btn lg" disabled={pending || !state.permissions?.['content.generate']} onClick={()=>void command('posts',{action:'generate-all'})}><Icon name="spark"/>Generate all</button></div>}</>;
}
