'use client';
import { useState } from 'react';
import { useStudio } from '../components/StudioProvider';
import { Header, Icon } from '../components/Design';

export default function LogsPage() {
  const {state,command,pending}=useStudio(); const [filter,setFilter]=useState('all'); const [query,setQuery]=useState('');
  const summary=state.summary; const openErrors=state.activity.filter(item=>item.level==='error'&&!item.done).length;
  const list=state.activity.filter(item=>(filter==='all'||filter==='err'&&['error','warning'].includes(item.level)||filter==='ai'&&item.actor==='AI'||filter==='team'&&!['AI','System'].includes(item.actor))&&(!query||`${item.message} ${item.actor}`.toLowerCase().includes(query.toLowerCase())));
  return <div className="logs"><aside className="logside"><section className="sec"><Header title="Last 24 hours"/><div className="sumrow">{[['Ideas',summary.ideas],['Picked',summary.picked],['Made',summary.made],['Approved',summary.approved],['Posted',summary.published],['Errors',openErrors]].map(([label,value])=><div key={label} className={label==='Errors'&&Number(value)>0?'e':''}><b>{value}</b><span>{label}</span></div>)}</div></section><section className="sec"><Header title="Connected tools"/><div className="conng">{state.connections.map(item=><div className={`cn ${item.connected?'':'bad'}`} key={item.id}><span className="st"/><span className="t"><b>{item.name}</b><small>{item.connected?item.purpose:item.detail}</small></span>{!item.connected&&<button className="btn sm" disabled={pending} onClick={()=>void command('sources',{action:'reconnect',key:item.id})}><Icon name="plug"/>Reconnect</button>}</div>)}</div></section></aside><section className="card pad sec feedcard"><div className="sechead"><h2>Activity</h2><div className="isearch"><span className="ic"><Icon name="search"/></span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search activity" aria-label="Search activity"/></div><div className="tools r">{[['all','All'],['err','Problems'],['ai','AI'],['team','Team']].map(([value,label])=><button className={`fchip ${filter===value?'on':''}`} key={value} onClick={()=>setFilter(value)}>{label}</button>)}</div></div><div className="feed">{list.length?list.map(item=>{const person=!['AI','System'].includes(item.actor);return <div className={`ev ${item.level==='error'&&!item.done?'err':''}`} key={item.id}><span className="tm">{item.at}</span><span className={`who2 ${item.actor==='AI'?'ai':person?'p':''}`}>{item.actor==='AI'?<Icon name="spark"/>:person?(item.actor==='You'?'You':item.actor.slice(0,2)):<Icon name={item.level==='error'?'alert':'zap'}/>}</span><span className="body"><b>{item.message}</b><span className="small muted">{item.actor}</span>{item.cause&&<dl className={`fixbox ${item.level==='warning'||item.done?'warn':''}`}><dt>Cause</dt><dd>{item.cause}</dd><dt>Fix</dt><dd>{item.done?'Fixed':item.fix}</dd></dl>}{item.connectionId&&!item.done&&<button className="btn sm" style={{alignSelf:'flex-start'}} disabled={pending} onClick={()=>void command('sources',{action:'reconnect',key:item.connectionId})}><Icon name="plug"/>Reconnect</button>}</span></div>}):<span className="muted" style={{padding:'14px 0'}}>{query?`No activity matches "${query}"`:'Nothing here'}</span>}</div></section></div>;
}
