'use client';
import { useState } from 'react';
import { useStudio } from '../components/StudioProvider';
import { Header, Icon } from '../components/Design';
import { formatEasternDate } from '../domain';

export default function LogsPage() {
  const { state, command, pending } = useStudio();
  const [filter, setFilter] = useState('all');
  const [query, setQuery] = useState('');
  const [page, setPage] = useState(1);
  const pageSize = 10;
  const openErrors = state.activity.filter(item => item.level === 'error' && !item.done).length;
  const list = state.activity.filter(item => (filter === 'all' || filter === 'err' && ['error', 'warning'].includes(item.level) || filter === 'jobs' && item.jobId || filter === 'team' && !['AI', 'System'].includes(item.actor)) && (!query || `${item.message} ${item.actor} ${item.detail || ''} ${item.cause || ''}`.toLowerCase().includes(query.toLowerCase())));
  const pageCount = Math.max(1, Math.ceil(list.length / pageSize));
  const currentPage = Math.min(page, pageCount);
  const pageItems = list.slice((currentPage - 1) * pageSize, currentPage * pageSize);
  const jobs = state.activity.filter(item => item.jobId);
  return <div className="logs"><aside className="logside"><section className="sec"><Header title="Last 24 hours"/><div className="sumrow">{[['Running', jobs.filter(job => ['running', 'queued', 'waiting', 'retry_pending'].includes(job.status || '')).length], ['Completed', jobs.filter(job => job.done).length], ['Errors', openErrors]].map(([label, value]) => <div key={label} className={label === 'Errors' && Number(value) > 0 ? 'e' : ''}><b>{value}</b><span>{label}</span></div>)}</div></section><section className="sec"><Header title="Tools"/><div className="conng">{state.connections.map(item => <div className={`cn ${item.connected ? '' : 'bad'}`} key={item.id}><span className="st"/><span className="t"><b>{item.name}</b><small>{item.detail || item.purpose}</small></span>{item.purpose === 'Publishing' && !item.connected && <a className="btn sm" href="https://zernio.com/dashboard/connections" target="_blank" rel="noreferrer"><Icon name="plug"/>Open Zernio</a>}</div>)}</div></section></aside>
    <section className="card pad sec feedcard"><div className="sechead"><h2>Activity</h2><div className="isearch"><span className="ic"><Icon name="search"/></span><input value={query} onChange={event => { setQuery(event.target.value); setPage(1); }} placeholder="Search activity" aria-label="Search activity"/></div><div className="tools r">{[['all', 'All'], ['err', 'Problems'], ['jobs', 'Jobs'], ['team', 'Team']].map(([value, label]) => <button className={`fchip ${filter === value ? 'on' : ''}`} key={value} onClick={() => { setFilter(value); setPage(1); }}>{label}</button>)}</div></div>
      <div className="feed">{pageItems.length ? pageItems.map(item => <div className={`ev ${item.level === 'error' && !item.done ? 'err' : ''}`} key={item.id}><time className="tm" dateTime={item.at}>{formatEasternDate(item.at)} · {new Date(item.at).toLocaleTimeString('en-US', { timeZone: 'America/New_York', hour: 'numeric', minute: '2-digit' })} ET</time><span className={`who2 ${item.actor === 'AI' ? 'ai' : ''}`}><Icon name={item.actor === 'AI' ? 'spark' : item.level === 'error' ? 'alert' : 'zap'}/></span><div className="body"><b>{item.message}</b><span className="small muted">{item.actor} · {item.detail}</span>{item.jobId && <div className="job-meta small muted"><span>{item.attempts} attempts</span>{item.providerJobId && <span>Provider ID: {item.providerJobId}</span>}{item.nextRetryAt && <span>Next sync: {new Date(item.nextRetryAt).toLocaleTimeString('en-US', { timeZone: 'America/New_York' })} ET</span>}</div>}
        {item.result?.model && <p className="small muted">Model: {item.result.model}</p>}{item.result?.ttsCredits != null ? <p className="small muted">Provider credits: {item.result.credits ?? 'pending'} video + {item.result.ttsCredits} voiceover</p> : item.result?.credits != null && <p className="small muted">Provider credits: {item.result.credits}</p>}{item.result?.usage?.cost != null && <p className="small muted">Recorded cost: ${item.result.usage.cost.toFixed(4)}</p>}{item.cause && <dl className="fixbox"><dt>Cause</dt><dd>{item.cause}</dd><dt>Fix</dt><dd>{item.fix}</dd></dl>}
        {item.jobId && ['failed', 'needs_attention'].includes(item.status || '') && state.permissions?.['jobs.retry'] && <button className="btn sm ghost" disabled={pending} onClick={() => { if (item.status === 'needs_attention' && !window.confirm('Have you checked the provider dashboard? Retrying an accepted request may incur another charge.')) return; void command('logs', { action: 'retry', id: item.jobId, confirmedProviderCheck: item.status === 'needs_attention' }); }}>Retry job</button>}
        {item.history?.length ? <details className="job-attempts"><summary>Attempt history</summary>{item.history.map((attempt, index) => <p key={index}>#{attempt.attempt} · {attempt.status} · {formatEasternDate(attempt.at)} {new Date(attempt.at).toLocaleTimeString('en-US', { timeZone: 'America/New_York', hour: 'numeric', minute: '2-digit' })} ET{attempt.cause && ` · ${attempt.cause}`}</p>)}</details> : null}
      </div></div>) : <p className="muted">No activity matches this view.</p>}</div>
      {list.length > 0 && <nav className="log-pagination" aria-label="Activity pages"><span className="small muted">Showing {(currentPage - 1) * pageSize + 1}–{Math.min(currentPage * pageSize, list.length)} of {list.length}</span><div><button className="btn ghost sm" disabled={currentPage === 1} onClick={() => setPage(value => Math.max(1, value - 1))}>Previous</button><span className="small muted" aria-live="polite">Page {currentPage} of {pageCount}</span><button className="btn ghost sm" disabled={currentPage >= pageCount} onClick={() => setPage(value => Math.min(pageCount, value + 1))}>Next</button></div></nav>}
    </section>
  </div>;
}
