'use client';
import { useState } from 'react';
import { useStudio } from '../components/StudioProvider';
import { Cover, Header, Icon, Who } from '../components/Design';
import { BarChart, MetricChart } from '../components/Charts';
import type { Post } from '../types';

function TopPosts({ posts, view, onOpen }: { posts: Post[]; view: 'cards'|'table'; onOpen: (id:number)=>void }) {
  if(view==='table')return <div className="tblwrap"><table className="tbl"><thead><tr><th>Post</th><th>Platform</th><th>Reach</th><th>Engagement</th></tr></thead><tbody>{posts.map(post=><tr key={post.id}><td style={{fontWeight:600}}>{post.title}</td><td>{post.platform}</td><td className="num">{post.reach?.toLocaleString()}</td><td className="num">{post.engagement}%</td></tr>)}</tbody></table></div>;
  return <>{posts.map(post=><button key={post.id} className="rowi" style={{border:0,padding:'6px 0'}} onClick={()=>onOpen(post.id)}><Cover bookId={post.bookId}/><span className="t"><b>{post.title}</b><small>{post.platform}<i className="sep"/>{post.reach?.toLocaleString()} reached<i className="sep"/>{post.clicks} link clicks</small></span><span className="pill ok">{post.engagement}%</span></button>)}</>;
}
export default function ResultsPage() {
  const {state,openPost}=useStudio();const results=state.results;const kpi=results.kpi;
  const [sort,setSort]=useState<'er'|'reach'>('er');const [view,setView]=useState<'cards'|'table'>('cards');
  const published=state.posts.filter(post=>post.stage==='published').sort((a,b)=>sort==='reach'?(b.reach||0)-(a.reach||0):(b.engagement||0)-(a.engagement||0));
  const short=(n:number)=>n>=1000?`${(n/1000).toFixed(n>=100000?0:1)}K`:String(n);
  const change=(current:number,previous:number,points=false)=>{const n=points?current-previous:(current-previous)/previous*100;return <small className={`delta ${n>=0?'up':'down'}`}>{n>=0?'+':''}{points?n.toFixed(1):Math.round(n)}{points?' points':'%'} vs previous 30 days</small>};
  return <><div className="sechead"><span className="chip">Last 30 days</span><span className="chip">Connected publishing platforms</span>{results.posts > 0 && <span className="small muted r">Synced data from connected posts</span>}</div>{results.posts === 0 ? <div className="card empty"><span className="ring"><Icon name="chart"/></span><h2>No performance data yet</h2><span>Verified metrics will appear after posts are published and analytics sync is connected.</span></div> : <><div className="kpis"><div className="kpi"><span>Reach</span><b>{short(kpi.reach[0])}</b>{change(...kpi.reach)}</div><div className="kpi"><span>Impressions</span><b>{short(kpi.impressions[0])}</b>{change(...kpi.impressions)}</div><div className="kpi hi"><span>Engagement rate</span><b>{kpi.er[0]}%</b>{change(...kpi.er,true)}</div><div className="kpi"><span>Link clicks</span><b>{kpi.clicks[0].toLocaleString()}</b>{change(...kpi.clicks)}</div><div className="kpi"><span>New followers</span><b>+{kpi.followers[0]}</b>{change(...kpi.followers)}</div></div>
    <section className="card pad sec"><Header title="Reach per week"><span className="small muted r">People who saw a post, last 8 weeks</span></Header><BarChart data={results.weeks} width={1200} height={260} max={40} step={10} format={value=>value?`${value}K`:'0'} label="Reach per week in thousands, last 8 weeks"/></section>
    <section className="card pad sec"><Header title="What works"><span className="small muted r">Engagement rate</span></Header><div className="wworks"><div className="wpanel"><MetricChart title="By format" data={results.byFormat.map(item=>({label:item.format[0].toUpperCase()+item.format.slice(1),value:item.engagement}))} label="Engagement rate by format"/></div><div className="wpanel"><MetricChart title="By platform" data={results.byPlatform.map(item=>({label:item.platform,value:item.engagement}))} label="Engagement rate by platform"/></div></div><div className="besttime"><Icon name="clock"/><span><b>Best time to post</b><span className="small muted">{results.best}</span></span></div><span className="small muted">Engagement rate is likes, comments, shares and saves, divided by reach.</span></section>
    <div className="two"><section className="card pad sec"><Header title="What the AI learned"><Who kind="ai"/></Header>{results.learned.map(item=><div className="learn" key={item.title}><span className="t"><b>{item.title}</b><span className="small muted">{item.use}</span></span><span className="chip ai"><Icon name="retry"/>Used next</span></div>)}</section><section className="card pad sec"><Header title="Top posts"><div className="tools r"><button className={`fchip ${sort==='er'?'on':''}`} onClick={()=>setSort('er')}>By engagement</button><button className={`fchip ${sort==='reach'?'on':''}`} onClick={()=>setSort('reach')}>By reach</button><span className="viewtog"><button className={view==='cards'?'on':''} aria-label="Card view" onClick={()=>setView('cards')}><Icon name="stack"/></button><button className={view==='table'?'on':''} aria-label="Table view" onClick={()=>setView('table')}><Icon name="list"/></button></span></div></Header><TopPosts posts={published} view={view} onOpen={openPost}/></section></div></>}</>;
}
