'use client';
import { useStudio } from '../components/StudioProvider';
import { Icon } from '../components/Design';
import { byTime, dayParts, formats } from '../domain';

export default function SchedulePage() {
  const { state, openPost, command, pending } = useStudio();
  const days=[-2,-1,0,1,2,3,4];
  const items=state.posts.filter(post=>post.day!=null&&['scheduled','published','review','revision'].includes(post.stage));
  const unslotted=state.posts.filter(post=>post.stage==='scheduled'&&post.day==null);
  return <><div className="conns"><span className="small muted" style={{fontWeight:600}}>Posting to</span>{state.connections.filter(item=>item.purpose==='Publishing').map(connection=>connection.connected?<span className="pill ok" key={connection.id}><Icon name="check"/>{connection.name}</span>:<button className="pill err" key={connection.id} disabled={pending} onClick={()=>void command('sources',{action:'reconnect',key:connection.id})}><Icon name="plug"/>{connection.name}: reconnect</button>)}<span className="pill"><Icon name="lock"/>{state.later.join(', ')} later</span></div>{unslotted.length>0&&<section className="card pad sec"><div className="sechead"><h2>Approved · choose a time</h2><span className="small muted">Approval is saved. These posts are held and will not publish until scheduled.</span></div>{unslotted.map(post=><button key={post.id} className="rowi" onClick={()=>openPost(post.id)}><b>{post.title}</b><span className="chip">{post.platform}</span><span className="small muted">Approved by {post.approvedBy}</span></button>)}</section>}<div className="wk">{days.map(day=>{const date=dayParts(day);const posts=items.filter(post=>post.day===day).sort(byTime);return <div className="dcol" key={day}><div className={`dhd ${day===0?'today':''} ${day<0?'past':''}`}><b>{date.d}</b><span>{day===0?'Today':date.wd}</span></div>{posts.length?posts.map(post=>{const status=post.error?'fail':post.stage==='published'?'live':post.stage==='scheduled'?'sched':'need';return <button className={`sp ${status}`} key={post.id} onClick={()=>openPost(post.id)}><span className="r"><span className="tm">{post.time}</span><Icon name={formats[post.format].icon}/>{post.platform==='Instagram'?'IG':'FB'}</span><b>{post.title}</b><span className="r small">{post.error?<span style={{color:'var(--err)',fontWeight:700}}>Failed</span>:post.stage==='published'?<><Icon name="check"/>Posted</>:post.stage==='scheduled'?<><Icon name="user"/>{post.approvedBy}</>:<span style={{color:'var(--need)',fontWeight:700}}>Not approved</span>}</span></button>}):<span className="none small muted" style={{padding:'8px 4px'}}>No posts</span>}</div>})}</div><div className="legend"><span><i style={{background:'var(--surf)',boxShadow:'inset 3px 0 0 var(--ok),inset 0 0 0 1.5px var(--line)'}}/>Approved, will post</span><span><i style={{background:'var(--needbg)',border:'1.5px dashed var(--need)'}}/>Waiting for approval</span><span><i style={{background:'var(--errbg)',border:'1.5px solid var(--err)'}}/>Failed</span><span><i style={{background:'var(--sunk)'}}/>Posted</span></div><div className="lockline"><Icon name="lock"/>Only approved posts go out. Waiting ones hold their slot.</div></>;
}
