'use client';
import { useStudio } from '../components/StudioProvider';
import { Header, Icon, Meter, money } from '../components/Design';
import { BarChart } from '../components/Charts';
import { dayParts, used } from '../domain';

export default function SpendPage() {
  const {state,command,pending}=useStudio();const spend=state.spend;const total=used(state);
  const tools=[['Captions','OpenRouter',spend.text],['Video','Creatify',spend.video],['Images','Predis',spend.image]] as const;
  const week=spend.week.map((value,index)=>({label:index===spend.week.length-1?'Today':dayParts(index-spend.week.length+1).wd,value}));
  return <><div className="grid3"><section className="card pad bigmeter"><Header title="Today"><span className="pill ai r">Recorded usage</span></Header><div className="fig"><b>{money(total)}</b><span className="muted">reference ${spend.cap}</span></div><Meter/><span className="muted">Provider credits are separate; unreported charges are not included.</span>{tools.map(([label,provider,value])=><div className="hbar" key={label}><span><b style={{display:'block',fontSize:14}}>{label}</b><span className="small muted">{provider}</span></span><span className="tr"><i style={{width:`${total?value/total*100:0}%`,background:'var(--ai)'}}/></span><span className="v">{money(value)}</span></div>)}</section><section className="card pad sec"><Header title="Reference budget"/><div className="stepper"><button aria-label="Lower the limit" disabled={pending || !state.permissions?.['spend.edit']} onClick={()=>void command('spend',{key:'cap',value:spend.cap-1})}>−</button><b>${spend.cap}</b><button aria-label="Raise the limit" disabled={pending || !state.permissions?.['spend.edit']} onClick={()=>void command('spend',{key:'cap',value:spend.cap+1})}>+</button></div><span className="muted">Budget enforcement is pending client confirmation. This value does not stop AI jobs yet.</span></section><section className="card pad sec"><Header title="Keeping costs low"/><div><button className="tg" disabled><span className="t"><b>Only picked ideas are made</b><small>Caption and media jobs start after picking</small></span><Icon name="lock"/><span className="sw on locked"/></button><div className="tg"><span className="t"><b>Configured model</b><small>OpenRouter uses the model selected in server settings</small></span><Icon name="lock"/></div></div></section></div><section className="card pad sec"><Header title="Last 7 days"><div className="tools r">{['Daily','Weekly','Monthly','Yearly'].map((label,index)=><button key={label} className={`fchip ${index===0?'on':''}`} disabled={index>0}>{label}{index>0&&<span className="soon">Soon</span>}</button>)}</div></Header><span className="small muted">Recorded USD usage per day; media credits are visible in Logs</span><BarChart data={week} width={1100} height={250} max={Math.max(12,Math.ceil(spend.cap/4)*4+4)} step={4} format={value=>`$${value.toFixed(2)}`} axisFormat={value=>`$${value}`} all cap={spend.cap} label="AI spend per day, last 7 days"/></section></>;
}
