'use client';
import { useStudio } from '../components/StudioProvider';
import { Header, Icon, Meter, money } from '../components/Design';
import { BarChart } from '../components/Charts';
import { dayParts, spendStatus, used } from '../domain';

export default function SpendPage() {
  const {state,command,pending}=useStudio();const spend=state.spend;const total=used(state);const status=spendStatus(state);
  const tools=[['Captions','OpenRouter',spend.text],['Video','Creatify',spend.video],['Images','Predis',spend.image]] as const;
  const week=spend.week.map((value,index)=>({label:dayParts(index-6).wd,value})).concat({label:'Today',value:+total.toFixed(2)});
  return <><div className="grid3"><section className="card pad bigmeter"><Header title="Today"><span className={`pill ${status==='stop'?'err':status==='near'?'need':'ok'} r`}>{status==='stop'?'Stopped at limit':status==='near'?'Near the limit':'On track'}</span></Header><div className="fig"><b>{money(total)}</b><span className="muted">of ${spend.cap}</span></div><Meter/><span className="muted">{money(Math.max(0,spend.cap-total))} left today</span>{tools.map(([label,provider,value])=><div className="hbar" key={label}><span><b style={{display:'block',fontSize:14}}>{label}</b><span className="small muted">{provider}</span></span><span className="tr"><i style={{width:`${total?value/total*100:0}%`,background:'var(--ai)'}}/></span><span className="v">{money(value)}</span></div>)}</section><section className="card pad sec"><Header title="Daily limit"/><div className="stepper"><button aria-label="Lower the limit" disabled={pending} onClick={()=>void command('spend',{key:'cap',value:spend.cap-1})}>−</button><b>${spend.cap}</b><button aria-label="Raise the limit" disabled={pending} onClick={()=>void command('spend',{key:'cap',value:spend.cap+1})}>+</button></div><span className="muted">At the limit, AI stops making content. Approved posts still go out.</span></section><section className="card pad sec"><Header title="Keeping costs low"/><div><button className="tg" disabled><span className="t"><b>Only picked ideas are made</b><small>Skipped ideas cost nothing</small></span><Icon name="lock"/><span className="sw on locked"/></button><button className="tg" disabled={pending} onClick={()=>void command('spend',{key:'efficientModel',value:!spend.efficientModel})}><span className="t"><b>Cheaper model for simple work</b><small>Captions and short text use a low-cost model</small></span><span className={`sw ${spend.efficientModel?'on':''}`} role="switch" aria-checked={spend.efficientModel}/></button></div></section></div><section className="card pad sec"><Header title="Last 7 days"><div className="tools r">{['Daily','Weekly','Monthly','Yearly'].map((label,index)=><button key={label} className={`fchip ${index===0?'on':''}`} disabled={index>0}>{label}{index>0&&<span className="soon">Soon</span>}</button>)}</div></Header><span className="small muted">AI spend per day against the daily limit</span><BarChart data={week} width={1100} height={250} max={Math.max(12,Math.ceil(spend.cap/4)*4+4)} step={4} format={value=>`$${value.toFixed(2)}`} axisFormat={value=>`$${value}`} all cap={spend.cap} label="AI spend per day, last 7 days"/></section></>;
}
