'use client';
import Link from 'next/link';
import { useStudio } from '../components/StudioProvider';
import { Cover, DueChip, Header, Icon, Meta, Meter, SourceChip, VersionChip, money } from '../components/Design';
import { byTime, dayParts, used } from '../domain';

const words = ['No','One','Two','Three','Four','Five','Six','Seven','Eight','Nine'];
const countWord = (count: number) => words[count] || String(count);
export default function TodayPage() {
  const { state, openPost, command, pending } = useStudio();
  const review = state.posts.filter(post=>post.stage==='review');
  const errors = state.posts.filter(post=>post.error);
  const today = state.posts.filter(post=>['scheduled','published'].includes(post.stage)&&post.day===0).sort(byTime);
  const ideas = state.posts.filter(post=>post.stage==='idea');
  const selected = state.posts.filter(post=>post.stage==='selected');
  const date = dayParts(0);
  const longDate = new Date().toLocaleDateString('en-US', { weekday: 'long', day: 'numeric', month: 'long' });
  return <>
    <section className="lede" aria-label="Summary for today"><span className="date">{longDate || `${date.wd} ${date.d} ${date.m}`}</span><p>{review.length ? <><Link href="/review" className="n-need">{countWord(review.length)} {review.length===1?'post':'posts'}</Link> {review.length===1?'waits':'wait'} for your approval.</> : 'Nothing is waiting for your approval.'}{errors.length > 0 && <> <Link href="/logs" className="n-err">{countWord(errors.length)} {errors.length===1?'post':'posts'}</Link> did not go out because the {errors[0].error}.</>} {today.filter(post=>post.stage==='scheduled'&&!post.error).length ? `${countWord(today.filter(post=>post.stage==='scheduled'&&!post.error).length)} more post goes out today, the next at ${today.find(post=>post.stage==='scheduled'&&!post.error)?.time}.` : 'Nothing else goes out today.'}</p></section>
    <div className="tiles"><Link className={`tile ${review.length?'need':'calm'}`} href="/review"><span className="ti"><Icon name="eye"/></span><b>{review.length}</b><span>To approve</span></Link><Link className={`tile ${errors.length?'err':'calm'}`} href="/logs"><span className="ti"><Icon name="alert"/></span><b>{errors.length}</b><span>{errors.length===1?'Error':'Errors'}</span></Link><Link className="tile calm" href="/schedule"><span className="ti"><Icon name="cal"/></span><b>{today.length}</b><span>Posting today</span></Link><Link className="tile" href="/spend"><span className="ti" style={{background:'var(--aibg)',color:'var(--ai)'}}><Icon name="spark"/></span><b className="num">{money(used(state))}</b><span>spent of ${state.spend.cap} today</span><Meter/><span className="sub num">{money(Math.max(0,state.spend.cap-used(state)))} left today</span></Link></div>
    <div className="two"><section className="sec"><Header title="Needs you"/><div className="rows">{review.map(post=><Link key={post.id} className="rowi" href={`/review?post=${post.id}`}><Cover bookId={post.bookId}/><span className="t"><b>{post.title}</b><small><Meta post={post}/><DueChip post={post}/><VersionChip post={post}/></small></span><span className="btn sm">Review</span></Link>)}{errors.map(post=><div key={post.id} className="rowi err"><span className="ico" style={{background:'var(--surf)',color:'var(--err)'}}><Icon name="alert"/></span><span className="t"><b>{post.title}</b><small>{post.error}. Did not post at {post.time}.</small></span><button className="btn sm" disabled={pending} onClick={()=>void command('sources',{action:'reconnect',key:post.platform==='Instagram'?'ig':'fb'})}><Icon name="plug"/>Reconnect</button></div>)}{selected.length>0 && <div className="rowi"><span className="ico" style={{background:'var(--aibg)',color:'var(--ai)'}}><Icon name="spark"/></span><span className="t"><b>{selected.length} picked ideas are ready to make</b><small>You see the real cost after each one is made</small></span><button className="btn sm ai" disabled={pending} onClick={()=>void command('posts',{action:'generate-all'})}>Generate</button></div>}</div></section>
    <section className="sec"><Header title="Posting today"><Link className="btn sm ghost r" href="/schedule">Schedule</Link></Header><div className="card pad tl">{today.map(post=><div className="it" key={post.id}><span className="tm">{post.time}</span><span className="ln"><i className={post.error?'fail':post.stage==='published'?'':'sched'}/></span><span><b style={{display:'block'}}>{post.title}</b><span className="small muted">{post.platform} · {post.error ? <span style={{color:'var(--err)',fontWeight:700}}>Failed</span> : post.stage==='published'?'Posted':`Approved by ${post.approvedBy}`}</span></span></div>)}</div><div className="sechead" style={{marginTop:6}}><h2>New ideas</h2><Link className="btn sm ghost r" href="/ideas">See {ideas.length}</Link></div><div className="rows">{ideas.slice(0,3).map(post=><button className="rowi" key={post.id} onClick={()=>openPost(post.id)} style={!post.human?{borderStyle:'dashed',borderColor:'var(--ailine)'}:undefined}><Cover bookId={post.bookId}/><span className="t"><b>{post.title}</b><small><SourceChip post={post}/><DueChip post={post}/></small></span><Icon name="chevR"/></button>)}</div></section></div>
  </>;
}
